id: P6557BD6F
initial_creation_type: input
source_metadata:
  title: 'BA: Daśabhūmikasūtra'
  language: bo
  volumes:
    49bf777350cd490c98122a562c974cfe:
      title: .txt
      base_file: .txt.txt
      work_id: W00897A98
  chapter_to_tile: {}
created_at: '2022-03-01T21:21:28.064810'
last_modified_at: '2022-03-01T21:21:28.064820'
